name: Package NuGet
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Bank.WebApi.Tests/Bank.WebApi.Tests.csproj

      - name: Build project
        run: dotnet build ./Bank.WebApi.Tests/Bank.WebApi.Tests.csproj --no-restore

      - name: Run tests
        run: dotnet test ./Bank.WebApi.Tests/Bank.WebApi.Tests.csproj --no-build --verbosity normal

      - name: Pack NuGet placeholder
        run: echo "No NuGet package to create for this lab"
