name: Publish DocFX Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install DocFX
        run: |
          dotnet tool install -g docfx

      - name: Add DocFX to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate DocFX documentation
        run: |
          docfx metadata docfx.json
          docfx build docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages

          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
